### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Cosmunn** [funkemunky/Iris-Issues#53]
**Describe the bug**
Fly (Type B) and GroundSpoof gives out false positives while climbing ladders or vines respectively, using 1.12 on a server running natively on 1.8 with ViaVersion (latest)

**Version Information**
- Iris Anticheat Version: 1.6.4
- Atlas Version: 1.1.1
- Bukkit/Spigot Version: PaperSpigot 1.8.8

**Server Logs**
There are no errors in the logs.

**How to re-create**
Steps:
1) I joined my server using 1.12, while it's 1.8 with ViaVersion
2) I climb ladders and vines
3) i cri everytiem

**Screenshots/Video**
https://streamable.com/54qiv
(test server was down but I could recreate it there in the past)

**Additional context**
Nothing really, thank you for reading <3

**Comment by FozzieHi** [comment]
Please try this with the latest version of [Iris](https://www.spigotmc.org/resources/iris-anticheat-advanced-cheat-detection-1-7-1-13.53721/)

**Comment by Cosmunn** [comment]
Oh hi! I have tried with Iris 1.7, although as funke understandably stopped working on it I didn't really follow up. It does still happen with any version 1.9 and up.

**Comment by FozzieHi** [comment]
Okay, I'll try and fix this for the next update, I'm taking over Iris.

**Comment by FozzieHi** [comment]
@Cosmunn I haven't managed to replicate this issue, I will hopefully push an update later today, if you are able to test that one.

**Comment by Cosmunn** [comment]
That's weird, I could even recreate it on the test server. Here's a more recent video, recorded the day 1.7 was released:

**1.9** (and up, same with every version): https://streamable.com/wbxmq
**1.8**: https://streamable.com/p61x9

I can surely test the update out! Thank you.

**Comment by FozzieHi** [comment]
I think the issue is fixed in the latest update, I will push it as soon as I can.

**Comment by FozzieHi** [comment]
@Cosmunn This should be fixed in the [latest update](https://www.spigotmc.org/resources/iris-anticheat-advanced-cheat-detection-1-7-1-13.53721/update?update=267187). Can you test it for me? I can't seem to replicate it in this version.

**Comment by Cosmunn** [comment]
Unfortunately, it still happens. ):

In case it helps, here's some stuff I haven't included in my prior report since I didn't know the /iris bugreport command was a thing:
**Config**: https://pastebin.com/Y8SjBHws
**Info**: https://pastebin.com/fgQHgBqG

The video is taking ages to upload for some reason and there's nothing really important in it, just the same I was showing before, but when it's done: https://streamable.com/zt6ta

**Comment by FozzieHi** [comment]
Can you DM me the IP of the server on Discord? Fozzie#0001
